"""内置风格模板 — 提示词与风格描述统一中文。"""

TEMPLATES: list[dict] = [
    {
        "id": "vox_papercut",
        "name": "Vox剪纸科普",
        "description": "低饱和扁平剪纸，适合硬核科普与纪录片节奏。",
        "category": ["科普", "剪纸"],
        "preview_cover": "/static/templates/vox_papercut.svg",
        "style_prefix": "Vox剪纸扁平插画，层叠剪纸边缘，低饱和，干净剪影，科普解说片气质",
        "negative_prompt": "写实照片，真人，真实人脸，三维渲染，日系动漫，模糊，噪点，水印，画面文字",
        "default_ratio": "16:9",
        "shot_duration_min": 4,
        "shot_duration_max": 15,
        "llm_system_addon": "按科普讲解节奏拆镜，台词口语化、信息密度适中，每镜一个清晰视觉焦点。全片保持同一剪纸画风与角色外形。",
        "seedream_config": {
            "ref_images": [],
            "strength": 0.7,
            "pipeline_mode": "full",
            "character_prompt": "符号化科普角色或简洁人形剪影，低细节面部，服装色块固定，全片外形一致",
            "extra_prompt": "层叠纸片边缘清晰，低饱和，单镜一个视觉焦点，避免写实皮肤与复杂纹理",
        },
        "seedance_config": {
            "motion_bias": "缓慢横移，轻推镜头，纸层轻微错动",
            "character_consistency": True,
        },
        "audio_config": {"voice_preset": "narrator_calm", "bgm_mood": "好奇纪录片"},
        "subtitle_config": {"font": "SourceHanSans", "position": "bottom"},
        "sort_order": 10,
        "is_active": True,
        "is_premium": False,
    },
    {
        "id": "kids_flat",
        "name": "儿童绘本扁平",
        "description": "柔和配色与圆润造型，适合儿童科普与故事。",
        "category": ["儿童", "绘本"],
        "preview_cover": "/static/templates/kids_flat.svg",
        "style_prefix": "儿童绘本扁平插画，柔和粉彩，圆润造型，友好角色，简洁背景",
        "negative_prompt": "恐怖，阴暗，写实照片，复杂纹理，血腥",
        "default_ratio": "16:9",
        "shot_duration_min": 3,
        "shot_duration_max": 12,
        "llm_system_addon": "用孩子听得懂的短句，每镜突出一个可爱视觉元素，节奏轻快。",
        "seedream_config": {
            "ref_images": [],
            "strength": 0.65,
            "pipeline_mode": "full",
            "character_prompt": "圆润可爱卡通角色，大眼睛简化五官，柔和配色服装，友好表情，全片同一角色外形",
            "extra_prompt": "粉彩柔光，背景简洁，造型圆润，适合儿童观看",
        },
        "seedance_config": {
            "motion_bias": "轻微弹跳感，柔和镜头漂移",
            "character_consistency": True,
        },
        "audio_config": {"voice_preset": "warm_storyteller", "bgm_mood": "俏皮轻快"},
        "subtitle_config": {"font": "RoundedSans", "position": "bottom"},
        "sort_order": 20,
        "is_active": True,
        "is_premium": False,
    },
    {
        "id": "chalk_whiteboard",
        "name": "粉笔白板手绘",
        "description": "黑板粉笔与白板简笔画，适合课堂讲解风。",
        "category": ["科普", "手绘"],
        "preview_cover": "/static/templates/chalk_whiteboard.svg",
        "style_prefix": "黑板粉笔与白板手绘讲解风，粉笔笔触，示意图箭头，素描线条",
        "negative_prompt": "写实照片，光滑三维，杂乱界面",
        "default_ratio": "16:9",
        "shot_duration_min": 4,
        "shot_duration_max": 15,
        "llm_system_addon": "偏讲解结构：定义→例子→对比，画面多用示意图与箭头。",
        "seedream_config": {
            "ref_images": [],
            "strength": 0.6,
            "pipeline_mode": "full",
            "character_prompt": "粉笔简笔人物或火柴人讲解者，线条简洁，特征固定，可重复识别",
            "extra_prompt": "黑板/白板底，箭头与示意图清晰，教学感构图",
        },
        "seedance_config": {
            "motion_bias": "线条逐步显现，镜头基本固定",
            "character_consistency": True,
        },
        "audio_config": {"voice_preset": "teacher_clear", "bgm_mood": "专注氛围"},
        "subtitle_config": {"font": "SourceHanSans", "position": "bottom"},
        "sort_order": 30,
        "is_active": True,
        "is_premium": False,
    },
    {
        "id": "magazine_collage",
        "name": "杂志拼贴",
        "description": "剪报拼贴与印刷纹理，适合文化话题与品牌故事。",
        "category": ["拼贴", "杂志"],
        "preview_cover": "/static/templates/magazine_collage.svg",
        "style_prefix": "杂志纸质拼贴，撕边，网纹印刷质感，层叠剪贴，大胆平面构图",
        "negative_prompt": "纯净矢量，写实皮肤，脏污发灰的色彩",
        "default_ratio": "9:16",
        "shot_duration_min": 4,
        "shot_duration_max": 12,
        "llm_system_addon": "视觉冲击优先，每镜一个强构图，文案短而有力。",
        "seedream_config": {
            "ref_images": [],
            "strength": 0.75,
            "pipeline_mode": "image_text",
            "character_prompt": "杂志剪贴人像剪影或印刷半调人物，外形与配色全片统一",
            "extra_prompt": "撕边纸质、网纹印刷、大胆色块，竖屏强构图",
        },
        "seedance_config": {
            "motion_bias": "图层轻微滑动旋转，纸张沙沙感",
            "character_consistency": True,
        },
        "audio_config": {"voice_preset": "urban_editorial", "bgm_mood": "时髦轻电子"},
        "subtitle_config": {"font": "DisplaySans", "position": "center"},
        "sort_order": 40,
        "is_active": True,
        "is_premium": False,
    },
    {
        "id": "pixel_retro",
        "name": "像素复古科普",
        "description": "8-bit/16-bit 像素风，适合科技史与游戏化讲解。",
        "category": ["像素", "复古"],
        "preview_cover": "/static/templates/pixel_retro.svg",
        "style_prefix": "复古像素画，16位有限色板，清晰像素块，简单游戏场景，无抗锯齿",
        "negative_prompt": "平滑渐变，写实照片，模糊像素",
        "default_ratio": "16:9",
        "shot_duration_min": 3,
        "shot_duration_max": 12,
        "llm_system_addon": "节奏偏游戏关卡感，信息点做成可辨识像素图标。",
        "seedream_config": {
            "ref_images": [],
            "strength": 0.7,
            "pipeline_mode": "full",
            "character_prompt": "16位像素小人角色，有限色板，外形与调色全片不变",
            "extra_prompt": "清晰像素块，无抗锯齿，游戏关卡式场景",
        },
        "seedance_config": {
            "motion_bias": "逐帧步进运动，轻微视差滚动",
            "character_consistency": True,
        },
        "audio_config": {"voice_preset": "retro_host", "bgm_mood": "8位好奇"},
        "subtitle_config": {"font": "PixelFont", "position": "bottom"},
        "sort_order": 50,
        "is_active": True,
        "is_premium": False,
    },
    {
        "id": "ink_guofeng",
        "name": "水墨国风",
        "description": "水墨留白与写意笔触，适合历史与文化短故事。",
        "category": ["国风", "水墨"],
        "preview_cover": "/static/templates/ink_guofeng.svg",
        "style_prefix": "中国水墨写意插画，富有表现力的笔触，大量留白，诗意氛围，淡雅墨色，非写实摄影",
        "negative_prompt": "写实照片，真人，真实人脸，霓虹，赛博朋克，日系动漫，欧美卡通，画面文字，字幕，水印",
        "default_ratio": "9:16",
        "shot_duration_min": 4,
        "shot_duration_max": 12,
        "llm_system_addon": "叙事偏意境与转折，台词可略文言白话混用，留白节奏。适合竖屏图文：每镜短标题+诗意副标题叠字，并写可朗读的旁白。",
        "seedream_config": {
            "ref_images": [],
            "strength": 0.7,
            "pipeline_mode": "image_text",
            "character_prompt": "水墨写意人物，简笔眉眼，宽袍或古装轮廓固定，墨色淡雅，全片同一人设",
            "extra_prompt": "大量留白，淡墨渲染，诗意意境，竖屏顶部可叠字",
        },
        "seedance_config": {
            "motion_bias": "墨晕渗开与消散，缓慢升降镜头，薄雾飘动",
            "character_consistency": True,
        },
        "audio_config": {"voice_preset": "guqin_narrator", "bgm_mood": "古筝氛围"},
        "subtitle_config": {"font": "KaiTi", "position": "top"},
        "sort_order": 60,
        "is_active": True,
        "is_premium": False,
    },
    {
        "id": "portrait_story",
        "name": "竖屏图文故事",
        "description": "竖屏插画叙事，适合历史人文短片。",
        "category": ["图文", "竖屏", "故事"],
        "preview_cover": "/static/templates/ink_guofeng.svg",
        "style_prefix": "统一二维概念插画，细腻光影与电影感构图，非写实摄影、非日系赛璐璐动漫，竖屏主体偏中下，顶部留白便于叠字，画面干净无文字",
        "negative_prompt": "写实照片，真人，真实人脸，摄影棚，电影真人剧照，日系动漫赛璐璐，画面文字，字幕，水印，标题字，logo，模糊",
        "default_ratio": "9:16",
        "shot_duration_min": 4,
        "shot_duration_max": 12,
        "llm_system_addon": "按故事节拍拆镜：起承转合。每镜 title 短标题、subtitle 叠字副标题、text 为可朗读旁白。画面必须全片统一插画风与人物外形，禁止某镜突然变成真人照片或另一套动漫风。",
        "seedream_config": {
            "ref_images": [],
            "strength": 0.7,
            "pipeline_mode": "image_text",
            "character_prompt": "故事主角外形固定：年龄感、发型发色、服装配色与辨识物全片一致，细腻插画五官，非真人照片",
            "extra_prompt": "竖屏构图，主体偏中下，顶部约1/4留白，电影感光影，画面内无文字",
        },
        "seedance_config": {
            "motion_bias": "缓慢推近或轻拉远",
            "character_consistency": True,
        },
        "audio_config": {"voice_preset": "narrator_calm", "bgm_mood": "叙事氛围"},
        "subtitle_config": {"font": "SourceHanSans", "position": "top"},
        "sort_order": 5,
        "is_active": True,
        "is_premium": False,
    },
]
